### ISSUE TITLE
Bug: Error when using w/ Astro

### ISSUE THREAD

**Issue by jasikpark** [czue/bluesky-comments#38]
```console
13:52:46 [ERROR] Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
  Stack trace:
    at /Users/calebjasik/Git/jasik-2.0/node_modules/.pnpm/bluesky-comments@0.12.0_react-dom@19.2.0_react@19.2.0__react@19.2.0/node_modules/bluesky-comments/dist/bluesky-comments.es.js:211:16
    [...] See full stack trace in the browser, or rerun with --verbose.
13:52:46 [ERROR] Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
  Stack trace:
    at /Users/calebjasik/Git/jasik-2.0/node_modules/.pnpm/bluesky-comments@0.12.0_react-dom@19.2.0_react@19.2.0__react@19.2.0/node_modules/bluesky-comments/dist/bluesky-comments.es.js:211:16
    [...] See full stack trace in the browser, or rerun with --verbose.
```

I'm trying to add this to my astro site - I'm on react 19.2.0, I wonder if that's the issue? Mind updating this to allow react 19 as a peer dep?

**Comment by czue** [comment]
Thanks. Are you able to elaborate on the request or provide clearer reproduciton steps? Is it that the library doesn't work with React 19 and needs to be updated? (I'm also a bit confused on the relationship between this and https://github.com/czue/bluesky-comments/issues/39 and whether they are the same issue or two separate ones)

**Comment by czue** [comment]
@jasikpark I just released `0.13.1` which should update the peer deps. Can you tell me whether that also addresses this (and close it if so)?

**Comment by jasikpark** [comment]
I'll test it out 👍 - I'm uncertain of whether #39 is relevant, but I'm definitely using React 19, so it seemed like a worthy change

**Comment by jasikpark** [comment]
<img width="510" height="231" alt="Image" src="https://github.com/user-attachments/assets/cf619252-e393-4323-a2eb-8ecab64fb110" />

Looks like I'm not getting the `cannot read properties of undefined (reading 'ReactCurrentDispatcher')` error anymore <3

Still not quite working though. Do I need to set a custom react jsx like you did in #40?

**Comment by jasikpark** [comment]
<img width="1260" height="143" alt="Image" src="https://github.com/user-attachments/assets/07765d45-03d7-41c0-9302-2a9c2c00a524" />

Seems like yes? Setting `jsxRuntime: "classic"` gets me this CORS error

**Comment by czue** [comment]
Hmm, I'm out of my area of expertise here, but my impression was that the `jsxRuntime: "classic"` thing is only necessary if you're using importmaps for react. Do you have more info about the error you're getting? A stack trace or console log etc. would be helpful.
